network:
  bonds:
    bond0:
       mtu: 1400
       addresses:
         - 192.168.102.102/24
       gateway4: 192.168.102.1
       nameservers:
           addresses: [ 172.16.13.0]
       interfaces:
         - eth1
         - eth2
       parameters:
         mode: 802.3ad
