network:
  ethernets:
    eth1: 
      dhcp4: no
    eth2: 
      dhcp4: no
  bonds:
    bond0:
       mtu: 1400
       interfaces:
         - eth1
         - eth2
       parameters:
         mode: 802.3ad
  vlans:
    vn1001:
      id: 1001
      link: bond0
    vn1002:
      id: 1002
      link: bond0
    vn1003:
      id: 1003
      link: bond0
    vn1101:
      id: 1101
      link: bond0
  bridges:
    blue:
       interfaces: [ vn1001 ]
    red:
       interfaces: [ vn1002 ]
    purple:
       interfaces: [ vn1003 ]
    green:
       interfaces: [ vn1101 ]
