network:
  ethernets:
    eth1:
       dhcp4: no
       mtu: 1400
       addresses:
         - 192.168.201.107/24
       gateway4: 192.168.201.1
       nameservers:
           addresses: [ 172.16.13.0]
