network:
    ethernets:
        enp1s0:
            dhcp4: false
            addresses: [ 172.16.102.254/24]
            routes:
            - to: 0.0.0.0/0
              via: 172.16.102.1
            nameservers:
              addresses:  [10.49.32.95, 10.49.32.97]
        enp7s0:
            dhcp4: false
            addresses: [ 192.168.41.11/24]
            routes:
            - to: 192.168.101.0/24
              via: 192.168.41.1
            - to: 192.168.102.0/24
              via: 192.168.41.1
        enp8s0:
            dhcp4: false
            addresses: [ 192.168.51.11/24]
            routes:
            - to: 192.168.201.0/24
              via: 192.168.51.1
    version: 2

