
sudo hostname svr1
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:40:a5
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.11.1/24, fc00:dead:beef:a011::1000:1/64]
      gateway4: 192.168.11.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname svr2
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:35:6e
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.12.2/24, fc00:dead:beef:a012::1000:2/64]
      gateway4: 192.168.12.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id

sudo hostname svr3
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:30:1c
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.11.3/24, fc00:dead:beef:a011::1000:3/64]
      gateway4: 192.168.11.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id

sudo hostname svr5
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:19:00:50:17
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.5/24, fc00:dead:beef:a101::1000:5/64]
      gateway4: 192.168.101.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF

sudo hostname svr2
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:20:97
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.102.2/24, fc00:dead:beef:a102::1000:2/64]
      gateway4: 192.168.102.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname svr4
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:61:96
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.13.4/24, fc00:dead:beef:0a13::1000:4/64]
      gateway4: 192.168.13.254
      gateway6:  fc00:dead:beef:0a13::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF
uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname svr3
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:73:cd
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.3/24, fc00:dead:beef:a101::1000:3/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF


sudo hostname kvm1
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/02_net.yaml
network:
  ethernets:
    eth1:
      dhcp4: no
      mtu: 9000
    eth2:
      dhcp4: no
      mtu: 9000
  bridges:
    ovs0:
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:1b:00:80:7e
      interfaces:
        - eth1
        - eth2
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id




sudo hostname kvm2
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bridges:
    ovs1:
      mtu: 9000
      addresses: [ 192.168.111.12/24, fc00:dead:beef:a111::1000:12/64]
      gateway4: 192.168.111.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:17:01:01:4c
      mtu: 9000
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id

sudo hostname kvm3
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bridges:
    ovs1:
      mtu: 9000
      addresses: [ 192.168.111.13/24, fc00:dead:beef:a111::1000:13/64]
      gateway4: 192.168.111.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:17:00:47:3a
      mtu: 9000
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id

sudo hostname kvm4
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bridges:
    ovs1:
      mtu: 9000
      addresses: [ 192.168.111.14/24, fc00:dead:beef:a111::1000:14/64]
      gateway4: 192.168.111.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:17:00:31:95
      mtu: 9000
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname kvm7
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bridges:
    ovs1:
      mtu: 9000
      addresses: [ 192.168.131.17/24, fc00:dead:beef:a131::1000:17/64]
      routes:
      - to: 0.0.0.0/0
        via: 192.168.131.254
        metric: 1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:17:00:93:8e
      mtu: 9000
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname kvm5
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bridges:
    ovs1:
      mtu: 9000
      addresses: [ 192.168.151.15/24, fc00:dead:beef:a151::1000:15/64]
      routes:
      - to: 0.0.0.0/0
        via: 192.168.151.254
        metric: 1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:17:00:e9:01
      mtu: 9000
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname kvm6
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bridges:
    ovs1:
      mtu: 9000
      addresses: [ 192.168.151.16/24, fc00:dead:beef:a151::1000:16/64]
      routes:
      - to: 0.0.0.0/0
        via: 192.168.151.254
        metric: 1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      openvswitch: {}
      interfaces:
      - bond0
  bonds:
    bond0:
      macaddress: 56:04:17:00:50:f6
      mtu: 9000
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname svr5
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth2:
      dhcp4: no
      addresses: [ 192.168.101.5/24, fc00:dead:beef:a101::1000:5/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:4c:e9
      interfaces:
        - eth1
        - eth2
      parameters:
         mode: 802.3ad
EOF


sudo hostname svr7
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      dhcp4: no
      addresses: [ 192.168.151.7/24, fc00:dead:beef:a151::1000:7/64]
      routes:
      - to: 0.0.0.0/0
        via: 192.168.151.254
        metric: 1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      macaddress: 56:04:17:00:86:5c
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

uuidgen | sed -e "s/-//g" | sudo tee /etc/machine-id


sudo hostname svr6
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:6c:c1
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.6/24, fc00:dead:beef:a101::1000:6/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF


sudo hostname lxc3
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
      addresses: [ 192.168.101.13/24, fc00:dead:beef:a101::1000:13/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  # bonds:
  #   bond0:
  #     macaddress: 56:04:1b:00:4c:e9
  #     interfaces:
  #       - eth1
  #       - eth2
  #     parameters:
  #        mode: 802.3ad
EOF

sudo hostname lxc4
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
      addresses: [ 192.168.101.14/24, fc00:dead:beef:a101::1000:14/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
  bonds:
    bond0:
      macaddress: 56:04:1b:00:71:f6
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
EOF

sudo hostname svr8
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:1b:00:26:5d
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.8/24, fc00:dead:beef:a101::1000:8/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF



set chassis aggregated-devices ethernet device-count 8
set interfaces ge-0/0/2 ether-options 802.3ad ae0
set interfaces ge-0/0/3 ether-options 802.3ad ae0
set interfaces ae0 native-vlan-id 101
set interfaces ae0 mtu 9000
set interfaces ae0 aggregated-ether-options lacp active
set interfaces ae0 unit 0 family ethernet-switching interface-mode trunk
set interfaces ae0 unit 0 family ethernet-switching vlan members vlan101
set interfaces irb unit 101 family inet address 10.0.0.1/31
set vlans vlan101 vlan-id 101
set vlans vlan101 l3-interface irb.101


set interfaces ge-0/0/0 ether-options 802.3ad ae1
set interfaces ge-0/0/1 ether-options 802.3ad ae1
set interfaces ae1 native-vlan-id 102
set interfaces ae1 aggregated-ether-options lacp active
set interfaces ae1 unit 0 family ethernet-switching interface-mode trunk
set interfaces ae1 unit 0 family ethernet-switching vlan members vlan102
set interfaces irb unit 102 family inet address 10.0.102.1/24
set vlans vlan102 vlan-id 102
set vlans vlan102 l3-interface irb.102



set interfaces ge-0/0/0 ether-options 802.3ad ae1
set interfaces ge-0/0/1 ether-options 802.3ad ae1
set interfaces ae1 native-vlan-id 103
set interfaces ae1 aggregated-ether-options lacp active
set interfaces ae1 unit 0 family ethernet-switching interface-mode trunk
set interfaces ae1 unit 0 family ethernet-switching vlan members vlan102
set interfaces irb unit 103 family inet address 10.0.103.1/24
set vlans vlan102 vlan-id 103
set vlans vlan102 l3-interface irb.103

sudo hostname svr2
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:20:00:8d:8b
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 10.0.103.10/24 ]
      gateway4: 10.0.103.1
EOF


sudo hostname lxc1
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:20:00:91:33
      interfaces:
        - eth1
        - eth2
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.21/24, fc00:dead:beef:a101::1000:21/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
EOF


set protocols bgp group to_dc1 neighbor 10.1.101.0 family inet any
set protocols bgp group to_dc1 neighbor 10.1.101.0 peer-as 65017
set protocols bgp group to_dc1 neighbor 10.1.101.2 family inet any
set protocols bgp group to_dc1 neighbor 10.1.101.2 peer-as 65018
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::0 family inet6 any
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::0 peer-as 65017
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::2 family inet6 any
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::2 peer-as 65018
set protocols bgp group to_dc1 neighbor 10.1.101.4 family inet any
set protocols bgp group to_dc1 neighbor 10.1.101.4 peer-as 65017
set protocols bgp group to_dc1 neighbor 10.1.101.6 family inet any
set protocols bgp group to_dc1 neighbor 10.1.101.6 peer-as 65018
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::4 family inet6 any
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::4 peer-as 65017
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::6 family inet6 any
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::6 peer-as 65018



set protocols bgp group to_dc1 neighbor 10.1.101.24 family inet any
set protocols bgp group to_dc1 neighbor 10.1.101.24 peer-as 65017
set protocols bgp group to_dc1 neighbor 10.1.101.26 family inet any
set protocols bgp group to_dc1 neighbor 10.1.101.26 peer-as 65018
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::24 family inet6 any
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::24 peer-as 65017
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::26 family inet6 any
set protocols bgp group to_dc1 neighbor fc00:dead:beef:ff01::26 peer-as 65018

set interfaces ge-0/0/1 unit 1003 vlan-id 1003
set interfaces ge-0/0/1 unit 1003 family inet address 10.1.101.25/31
set interfaces ge-0/0/1 unit 1003 family inet6 address fc00:dead:beef:ff01::25/127
set interfaces ge-0/0/2 unit 1003 vlan-id 1003
set interfaces ge-0/0/2 unit 1003 family inet address 10.1.101.27/31
set interfaces ge-0/0/2 unit 1003 family inet6 address fc00:dead:beef:ff01::27/127