network:
  ethernets:
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bonds:
    bond0:
      mtu: 1350
      macaddress: 56:04:1a:00:28:42
      interfaces:
        - eth1
        - eth2
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.103/24, fc00:dead:beef:101::10:103/64]
      gateway4: 192.168.101.1
      gateway6: fc00:dead:beef:101::1
      nameservers:
        addresses: [172.16.11.0]
       
