
network:
  ethernets:
    eth0:
      dhcp4: false
      addresses: [ 172.16.10.204/24 ]
#      nameservers:
#         addresses: [ 66.129.233.81 , 66.129.233.82]
#      routes:
#        - to: 0.0.0.0/0
#          via: 172.16.10.1
#          metric: 1
    eth1:
      dhcp4: false
    eth2:
      dhcp4: false
      mtu: 9000
      addresses: [ 10.100.1.149/31 ,0::ffff:10.100.1.149/127]
    eth3:
      dhcp4: false
      mtu: 9000
      addresses: [ 10.100.1.151/31 ,0::ffff:10.100.1.151/127]
  vlans:
    vlan1:
      link: eth1
      id: 1
      addresses: [192.168.255.6/31, 2001:dead:beef:ffff::ffff:6/127]
    vlan10:
      link: eth1
      id: 10
      addresses: [192.168.255.14/31, 2001:dead:beef:ffff::ffff:14/127]
