network:
  ethernets:
    eth0:
      addresses : ['172.16.10.5/24']
      nameservers:
         addresses: ['10.49.32.95', '10.49.32.97']
      routes: 
       - to: 0.0.0.0/0
         via: 172.16.10.254
         metric: 1
    eth1:
      dhcp4: false
      mtu: 9000
    eth2:
      dhcp4: false
      mtu: 9000
    eth3:
      dhcp4: false
      mtu: 9000
    eth4:
      dhcp4: false
      mtu: 9000
  vlans:
    eth1v101:
      id: 101
      link: eth1
    eth3v101:
      id: 101
      link: eth3
    eth1v102:
      id: 102
      link: eth1
    eth3v102:
      id: 102
      link: eth3
    eth1v103:
      id: 103
      link: eth1
    eth3v103:
      id: 103
      link: eth3
    eth1v104:
      id: 104
      link: eth1
    eth3v104:
      id: 104
      link: eth3
    eth1v105:
      id: 105
      link: eth1
    eth3v105:
      id: 105
      link: eth3
  bridges:
    pe11gev101:
      interfaces: [eth1v101]
    ce1eth1: {}
    pe12gev101:
      interfaces: [eth3v101]
    ce2eth1: {}
    pe11gev102:
      interfaces: [eth1v102]
    ce3eth1: {}
    pe12gev102:
      interfaces: [eth3v102]
    ce4eth1: {}
    pe11gev103:
      interfaces: [eth1v103]
    pe12gev103:
      interfaces: [eth3v103]
    pe11gev104:
      interfaces: [eth1v104]
    pe12gev104:
      interfaces: [eth3v104]
    ce5eth1: {}
    ce6eth1: {}
    pe11gev105:
      interfaces: [eth1v105]
    pe12gev105:
      interfaces: [eth3v105]
    ce7eth1: {}
    ce8eth1: {}
