
network:
  ethernets:
    eth1:
      mtu: 1350
      dhcp4: false
      addresses: [ 192.168.101.11/24 ]
      gateway4: 192.168.101.1
      nameservers:
          addresses: [172.16.11.0]



network:
  ethernets:
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bonds:
    bond0:
       mtu: 1350
       macaddress: 56:04:19:00:68:e9
       interfaces:
         - eth1
         - eth2
       parameters:
         mode: 802.3ad
  vlans:
    vlan101:
      id: 101
      link: bond0
    vlan102:
      id: 102
      link: bond1
  bridges:
    br101:
      interfaces: [vlan101]
    br102:
      interfaces: [vlan102]
