network:
  ethernets:
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
  bonds:
    bond0:
       mtu: 1350
       macaddress: 56:04:17:00:aa:03
       interfaces:
         - eth1
         - eth2
       parameters:
         mode: 802.3ad
       addresses: [ 192.168.102.19/24]
       gateway4: 192.168.102.1
       nameservers:
          addresses: [172.16.11.0]
